name: CI/CD Pipeline for SAP CAP App

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest Ubuntu environment

    steps:
    - name: Check out code
      uses: actions/checkout@v2   # Checkout the repo's code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'   # Set up Node.js environment

    - name: Install dependencies
      run: npm install   # Install your project dependencies

    - name: Run Selenium Tests
      run: |
        npm install selenium-webdriver   # Install Selenium if not already in package.json
        npm run test:selenium   # Run Selenium tests (make sure you have a script in package.json)

    - name: Run JMeter Tests
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz  # Download JMeter
        tar -xvzf apache-jmeter-5.4.1.tgz   # Extract the JMeter binary
        cd apache-jmeter-5.4.1/bin
        ./jmeter -n -t /path/to/your/test-plan.jmx -l result.jtl   # Replace with the correct path to your JMeter test plan

    - name: Build the App
      run: npm run build   # Build the app (if needed)

    - name: Deploy to SAP BTP (Optional)
      if: github.ref == 'refs/heads/main'  # Only deploy when pushed to main
      run: |
        echo "Deploying to SAP BTP..."
        # Add your SAP BTP deployment commands here, for example:
        # cf push my-cap-app
