name: CI/CD Pipeline for SAP CAP App

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest Ubuntu environment

    steps:
    - name: Check out code
      uses: actions/checkout@v2   # Checkout the repo's code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'   # Set up Node.js environment

    - name: Install dependencies
      run: npm install   # Install your project dependencies

    - name: Build the App
      run: npm run build   # Build the app (if needed)

    - name: Start the App Locally (Optional - For testing the build step)
      run: |
        npm run start &
        sleep 20  # Wait for the app to start before continuing (adjust as necessary)
        curl --fail http://localhost:4004 || exit 1  # Test if the app is running correctly

    - name: Deploy to SAP BTP (Only on main branch)
      if: github.ref == 'refs/heads/main'  # Only deploy when pushed to main
      run: |
        echo "Deploying to SAP BTP..."
        # Ensure you have a manifest.yml file and that you are logged in to SAP BTP
        cf push my-cap-app  # Replace with actual deployment command
